/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.ImageIcon;

/**
 *
 * @author danie
 */
public class Animacion extends javax.swing.JPanel implements Runnable {

    /**
     * Creates new form lienzo
     */
    int x = this.getWidth() / 2;
    int y = this.getHeight() / 2;
    Thread hilo;

    public Animacion() {
        initComponents();
        this.setSize(1560, 810);
        hilo = new Thread(this);
    }

    public void paint(Graphics g) {
        Dimension tamanio = getSize();
        ImageIcon imagenFondo = new ImageIcon(getClass().getResource("/Imagenes/procesocivil.png"));
        g.drawImage(imagenFondo.getImage(), 0, 0, tamanio.width, tamanio.height, null);
        setOpaque(false);
        super.paintComponent(g);
        g.setColor(Color.blue);
        g.fillOval(x, y, 15, 15);
    }

    public void inicio() {
        hilo.start();
    }

    public void pausa() {
        hilo.suspend();
    }

    public void continuar() {
        hilo.resume();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new javax.swing.OverlayLayout(this));
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void run() {
        try {
            while (true) {
                for (int i = 1; i <= 6; i++) {
                    while (x <= ((getWidth() / 6 - 3) * i) - 20) {
                        Thread.sleep(50);
                        x += 5;
                        repaint();
                    }
                    while (y < ((getHeight() / 6 - 7) * i) - 20) {
                        Thread.sleep(50);
                        y += 5;
                        repaint();
                    }
                }
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
