/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author danie
 */
public class Lienzo extends javax.swing.JPanel implements Runnable {

    /**
     * Creates new form lienzo
     */
    int x = this.getWidth() / 2;
    int y = this.getHeight() / 2;
    Thread hilo;

    public Lienzo() {
        initComponents();
        hilo = new Thread(this);
    }

    public void paint(Graphics g) {
        g.setColor(getBackground());
        g.fillRect(0, 0, getWidth(), getHeight());
        g.setColor(Color.red);
        g.fillOval(x, y, 15, 15);
    }

    public void inicio() {
        hilo.start();
    }

    public void pausa() {
        hilo.suspend();
    }

    public void continuar() {
        hilo.resume();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void run() {
        try {
            while (true) {
                for (int i = 1; i <= 6; i++) {
                    while (x <= (getWidth() / 6 * i) - 20) {
                        Thread.sleep(50);
                        x += 5;
                        repaint();
                    }
                    while (y < (getHeight() / 6 * i) - 20) {
                        Thread.sleep(50);
                        y += 5;
                        repaint();
                    }
                }
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
